packages:
  - tooling/*
  - packages/@core
  - packages/plugins/*
  - apps/*
  - docs

catalog:
  '@biomejs/biome': ^1.9.4
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@iconify/vue': ^5.0.0
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@types/node': ^24.10.9
  '@vee-validate/zod': ^4.15.1
  '@vitejs/plugin-vue': ^6.0.3
  '@vitejs/plugin-vue-jsx': ^5.1.3
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^14.1.0
  '@vueuse/integrations': ^14.1.0
  ant-design-vue: ^4.2.6
  autoprefixer: ^10.4.23
  axios: ^1.13.4
  clsx: ^2.1.1
  consola: ^3.4.2
  cross-env: ^10.1.0
  dayjs: ^1.11.19
  defu: ^6.1.4
  element-plus: ^2.13.1
  es-toolkit: ^1.44.0
  esbuild: ^0.25.12
  happy-dom: ^17.6.3
  jiti: ^2.6.1
  lefthook: ^2.0.16
  lucide-vue-next: ^0.553.0
  naive-ui: ^2.43.2
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  postcss: ^8.5.6
  rimraf: ^6.1.2
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.19
  tailwindcss-animate: ^1.0.7
  turbo: ^2.7.6
  typescript: ^5.9.3
  unbuild: ^3.6.1
  vee-validate: ^4.15.1
  vite: ^7.3.1
  vitest: ^3.2.4
  vue: ^3.5.27
  vue-i18n: ^11.2.8
  vue-router: ^4.6.4
  vue-tsc: ^3.2.4
  zod: ^3.25.76
  zod-defaults: 0.1.3

overrides:
  clsx: 'catalog:'
  esbuild: 'catalog:'
  jiti: 'catalog:'
  pinia: 'catalog:'
  vue: 'catalog:'
