packages:
  - 'tooling/*'
  - 'packages/@core'
  - 'packages/plugins/*'
  - 'apps/*'
  - 'docs'

overrides:
  clsx: 'catalog:'
  esbuild: 'catalog:'
  jiti: 'catalog:'
  pinia: 'catalog:'
  vue: 'catalog:'

catalog:
  # 核心框架
  vue: ^3.5.27
  typescript: ^5.9.3
  vite: ^7.3.1
  
  # 构建工具
  '@vitejs/plugin-vue': ^6.0.3
  '@vitejs/plugin-vue-jsx': ^5.1.3
  '@vueuse/core': ^14.1.0
  '@vueuse/integrations': ^14.1.0
  
  # 路由和状态管理
  vue-router: ^4.6.4
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  
  # HTTP 和工具
  axios: ^1.13.4
  dayjs: ^1.11.19
  es-toolkit: ^1.44.0
  
  # UI 库
  ant-design-vue: ^4.2.6
  element-plus: ^2.13.1
  naive-ui: ^2.43.2
  lucide-vue-next: ^0.553.0
  
  # 国际化
  vue-i18n: ^11.2.8
  '@intlify/unplugin-vue-i18n': ^6.0.8
  
  # 表单验证
  vee-validate: ^4.15.1
  '@vee-validate/zod': ^4.15.1
  zod: ^3.25.76
  zod-defaults: 0.1.3
  
  # 样式
  tailwindcss: ^3.4.19
  tailwind-merge: ^2.6.0
  tailwindcss-animate: ^1.0.7
  autoprefixer: ^10.4.23
  postcss: ^8.5.6
  
  # 代码质量
  '@biomejs/biome': ^1.9.4
  lefthook: ^2.0.16
  
  # Monorepo 工具
  turbo: ^2.7.6
  '@changesets/cli': ^2.29.8
  '@changesets/changelog-github': ^0.5.2
  
  # TypeScript
  '@types/node': ^24.10.9
  vue-tsc: ^3.2.4
  
  # 测试
  vitest: ^3.2.4
  '@vue/test-utils': ^2.4.6
  happy-dom: ^17.6.3
  
  # 其他工具
  unbuild: ^3.6.1
  rimraf: ^6.1.2
  cross-env: ^10.1.0
  esbuild: ^0.25.12
  jiti: ^2.6.1
  clsx: ^2.1.1
  defu: ^6.1.4
  consola: ^3.4.2
