spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/yxboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果) 以下解密结果为123456
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  # Redis 若设有密码自行添加配置password
  redis:
    host: localhost
    port: 6379
    password: 123456


yxboot:
  upload:
    model: local
    local:
      enable: true
      path-prefix: /srv/yxboot/images/
      url-prefix: http://admin.yxboot.com/images/
      rewrite-file-name: false
    oss:
      enable: true
      endpoint: xxx
      accessKey: xxx
      secretKey: xxx
      bucketName: xxx
      rewrite-file-name: true